apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  creationTimestamp: "2021-01-12T13:57:58Z"
  generation: 4
  name: cluster
  resourceVersion: "243432"
  selfLink: /apis/config.openshift.io/v1/oauths/cluster
  uid: ada0655d-9b48-44e7-8f55-067a1311f9ef
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpasswd-secret
    mappingMethod: claim
    name: htpasswd_provider
    type: HTPasswd
  templates:
    error:
      name: error-template
    login:
      name: login-template
    providerSelection:
      name: providers-template
